### ISSUE TITLE
Implement API for Source Registry service

### ISSUE THREAD

**Issue by idomingu** [giros-dit/semantic-data-aggregator#25]
## Description

Design and implement a REST API that enables DSF users to build register data sources. The goal is to introduce an abstraction layer so that users do not need to interact directly with NGSI-LD complexity.

## Tasks

- [ ] Implement REST API using FastAPI framework
- [ ] Enable Network Telemetry source in the API
- [ ] Add Redis database into SDA for storing sensitive data
- [ ] Implement REST API in network-telemetry-explorer to receive NGSI-LD notifications
- [ ] Document in CLARITY D4.3
