### ISSUE TITLE
Implement API for Consumer Registry service

### ISSUE THREAD

**Issue by idomingu** [giros-dit/semantic-data-aggregator#26]
## Description

Design and implement a REST API that enables DSF users to build register data consumers. The goal is to introduce an abstraction layer so that users do not need to interact directly with NGSI-LD complexity.

## Tasks

- [ ] Implement REST API using FastAPI framework
- [ ] Enable DataLake consumer in the API
- [ ] Add Redis database into SDA for storing sensitive data
- [ ] Implement REST API in data-lake-explorer to receive NGSI-LD notifications
- [ ] Document in CLARITY D4.3
