### ISSUE TITLE
Implement API for Data Pipeline Provisioner service

### ISSUE THREAD

**Issue by idomingu** [giros-dit/semantic-data-aggregator#27]
## Description

Design and implement a REST API that enables DSF users to build data pipelines. The goal is to introduce an abstraction layer so that users do not need to interact directly with NGSI-LD complexity.

## Tasks

- [ ] Implement REST API using FastAPI framework
- [ ] Redefine task orchestration
- [ ] Document in CLARITY D4.3
