### ISSUE TITLE
Implement API for Capabilities Exposure service

### ISSUE THREAD

**Issue by idomingu** [giros-dit/semantic-data-aggregator#28]
## Description

Design and implement a REST API that enables DSF users to inspect/register capabilities of data sources and data consumers that have been registered in the SDA. The goal is to introduce an abstraction layer so that users do not need to interact directly with NGSI-LD complexity.

## Tasks

- [ ] Implement REST API using FastAPI framework
- [ ] Enable NetworkTelemetry source and DataLake consumer in the API
- [ ] Document in CLARITY D4.3
