### ISSUE TITLE
Implement dispatch agent for Data Lake

### ISSUE THREAD

**Issue by idomingu** [giros-dit/semantic-data-aggregator#40]
## Description

Develop combination of SDA tasks responsible for writing data into IDCC's Data Lake.

## Tasks

- [ ] Develop NiFi template
- [x] giros-dit/semantic-metrics-datamodels#35
- [ ] Implement orchestration logic in weaver
- [ ] Document in D4.3

## Dependencies

- [x] #27 

The orchestration logic in weaver depends on the redefinition of Task orchestration.
