### ISSUE TITLE
Integration of SDA with ML and DL models in PALANTIR

### ISSUE THREAD

**Issue by aams-telefonica** [giros-dit/semantic-data-aggregator#86]
## DESCRIPTION
This issue is to research how the integration of Machine Learning and Deep Learning models is done in the PALANTIR project, documenting important notes and things to consider when trying to integrate SDA to be suitable for a ML and DL model as a consumer.

## TASKS
- [x] giros-dit/semantic-metrics-datamodels#69. The trained model uses two features that are not available in the actual aggregated Netflowv9 model, need to include them in the model. The features are "ratio-bytes-in-per-out" and "ratio-pckts-in-per-out".
- [x] giros-dit/semantic-metrics-datamodels#70. This metrics have to be computed also in the aggregation app.
- [x] To make possible the CDS (Cryptomining Detection System) to receive the data there are 3 possible solutions:
   - Add this new features and the ones needed to the actual Serializer2Csv app, and choose the ones needed in the CDS.
   - Use the output of the aggregation app as input for the CDS and process the message as a JSON to later construct a numpy array.
   - giros-dit/semantic-metrics-datamodels#71. **Create another specific serializer for the CDS that only outputs the needed values.**
- [x] Create an application to detect cryptomining traffic using machine learning. Use as inputs: the trained model ("RandomForestTrained.joblib"), a kafka broker, a kafka input topic, a kafka output topic . The application reads from a Kafka topic and outputs the result in other topic.
- [x] Deploy the whole pipeline in kubernetes

## NOTES
Confluence [Progress update on T5.3](https://confluence.i2cat.net/display/PAL/Progress+update+on+T5.3)
Working on porting the anomaly detection and threat classification models to a Spark cluster
- For anomaly detection, we experiment with Elephas to load Keras/Tensorflow models to Spark
- For threat classification, we use Sklearn which already supports Spark integration.
- Plan to work on Kafka-Spark integration to read streaming data as dataframes.

[Proposed Pipeline (TBD)](https://confluence.i2cat.net/download/attachments/120195330/image2021-2-4_13-43-13.png?version=1&modificationDate=1612438990000&api=v2)
[Model Lifecycle Management (MLOps) proposed pipeline (TBD)](https://confluence.i2cat.net/download/attachments/120195330/image2021-2-4_13-44-19.png?version=1&modificationDate=1612439056000&api=v2)

A tool named nfcapd has been used for collecting netflows in the Collector module. **These collected netflows are the input of the DCP subcomponent**. Kafka connectors in the Data Collection module implemented Kafka Connect API have been used for ingesting data to Kafka and fetching data from Kafka to insert them to Elasticsearch. **Data Preprocessing module is a Spark  streaming application** which preprocess and anonymizes collected data, using the Data Anonymization module, which **implements [Crypto-PAn](https://en.wikipedia.org/wiki/Crypto-PAn) algorithm**.

As the communication bus in PALANTIR is Kafka, the applications for Anonymization, Data Preprocessing and Anomally detection are developed with Spark Streaming using Kubernetes. Hence, the SDA does not have to take into consideration anything new but to write in the proper Kafka topic with the correct Data Structure.

A benchmark is done in the D5.1 section 4.1.2 Figure 20: [Benchmark D5.1](https://confluence.i2cat.net/download/attachments/120193857/PALANTIR_D5.1_Hybrid_Threat_Intelligence_Framework_1st-release_v1.0_final.pdf?version=1&modificationDate=1643014282000&api=v2&download=true)

The training and testing models for classification are also developed using Spark, in particular Spark v3.2 [distributed ML framework](https://www.jmlr.org/papers/volume17/15-237/15-237.pdf)

## QUESTIONS
- What is the format that the Spark Streaming application reads from Kafka?

## DOCUMENTATION
- To integrate [scikit-learn with Spark](https://databricks.com/blog/2016/02/08/auto-scaling-scikit-learn-with-apache-spark.html)
- [spark-learn](https://github.com/databricks/spark-sklearn) appears to be deprecated and now it is recommended to use [joblib-spark](https://github.com/joblib/joblib-spark)
