### ISSUE TITLE
Implement registration of transport network devices

### ISSUE THREAD

**Issue by idomingu** [giros-dit/semantic-data-aggregator#90]
# Description

In the scope of CLARITY project, implement the registration of transport network devices as data sources of the DSF. The registration of a device triggers mechanisms of context auto-discovery as documented in D4.3. The component responsible for the discovery of capabilities is the Telemetry Explorer.

# Tasks

- [x] Update clarity scenario with Arista routers
- [x] Implement discovery of capabilities with NETCONF
- [x] Implement telemetry-explorer service to handle device registrations
